### ISSUE TITLE
Queries to HostedService scim/users/?filter=externalId%20eq%20bjensen results in 500 error

### ISSUE THREAD

**Issue by iaiken** [Azure/AzureAD-BYOA-Provisioning-Samples#23]
I was finally able to get the SampleProvider working after decompiling the code (seriously, this needs  far more extensive documentation and examples than have been provided). 

Executing the following query results in 500 error response:

http://localhost:47035/scim/users/?filter=externalId%20eq%20bjensen

I can see the response object, but the serializer in the demo is falling down. 

```
<Error>
  <Message>An error has occurred.</Message>
  <ExceptionMessage>
Type 'Microsoft.SystemForCrossDomainIdentityManagement.QueryResponse' with data contract name 'QueryResponse:http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.
  </ExceptionMessage>
  <ExceptionType>
    System.Runtime.Serialization.SerializationException
  </ExceptionType>
  <StackTrace>
    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
    at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.DataContractSerializer.WriteObject(XmlWriter writer, Object graph) at System.Net.Http.Formatting.XmlMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)
    at System.Net.Http.Formatting.XmlMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()
  </StackTrace>
</Error>
```
How does this contract binding even work? Also, this uri is dead...

'QueryResponse:http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement'

**Comment by craigmcm** [comment]
We’d like to help, but we don’t have enough information yet to do so.

            I was finally able to get the SampleProvider working after decompiling the code (seriously, this needs far more extensive documentation and examples than have been provided).
For us to fix the documentation, please explain why it was necessary to decompile the code to get any of the samples working.

            Executing the following query results in 500 error response:
Again, to know why that’s happening in your case, we’d need to know the circumstances under which it occurred.  For example, you might be running a particular sample of ours, and the error occurs.  If you provide us the steps to reproduce the problem, we can fix it.


Also, this uri is dead...
…http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fschemas.datacontract.org%2F2004%2F07%2FMicrosoft.SystemForCrossDomainIdentityManagement&data=02%7C01%7Ccraigmcm%40microsoft.com%7Cdbfc5c5b1a4e49fdaa3308d68ba37b92%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636849931599759441&sdata=uueZxu%2BzZ9ejNA2cm9V78mRBd4UAOPmS9kn6wpDJRIE%3D&reserved=0>

Do you mean, “if http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement is assumed to be a uniform resource locator, then it does not refer to any valid location, so that, for example, directing a browser to that address leads to a 404?  If so, then that is because it is indeed a uniform resource identifier, not a uniform resource locator.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

**Comment by craigmcm** [comment]
(It’s unhelpful of us to have used http as the scheme, because that makes the identifier appear as if it is also a locator.)

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

From: Craig McMurtry
Sent: Tuesday, February 5, 2019 12:51 PM
To: 'Azure/AzureAD-BYOA-Provisioning-Samples' <reply@reply.github.com>; Azure/AzureAD-BYOA-Provisioning-Samples <AzureAD-BYOA-Provisioning-Samples@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [Azure/AzureAD-BYOA-Provisioning-Samples] Queries to HostedService scim/users/?filter=externalId%20eq%20bjensen results in 500 error (#23)

We’d like to help, but we don’t have enough information yet to do so.

            I was finally able to get the SampleProvider working after decompiling the code (seriously, this needs far more extensive documentation and examples than have been provided).
For us to fix the documentation, please explain why it was necessary to decompile the code to get any of the samples working.

            Executing the following query results in 500 error response:
Again, to know why that’s happening in your case, we’d need to know the circumstances under which it occurred.  For example, you might be running a particular sample of ours, and the error occurs.  If you provide us the steps to reproduce the problem, we can fix it.


Also, this uri is dead...
…http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fschemas.datacontract.org%2F2004%2F07%2FMicrosoft.SystemForCrossDomainIdentityManagement&data=02%7C01%7Ccraigmcm%40microsoft.com%7Cdbfc5c5b1a4e49fdaa3308d68ba37b92%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636849931599759441&sdata=uueZxu%2BzZ9ejNA2cm9V78mRBd4UAOPmS9kn6wpDJRIE%3D&reserved=0>

Do you mean, “if http://schemas.datacontract.org/2004/07/Microsoft.SystemForCrossDomainIdentityManagement is assumed to be a uniform resource locator, then it does not refer to any valid location, so that, for example, directing a browser to that address leads to a 404?  If so, then that is because it is indeed a uniform resource identifier, not a uniform resource locator.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

**Comment by iaiken** [comment]
Hi Craig,

I am working from the following project with no changes:

https://github.com/Azure/AzureAD-BYOA-Provisioning-Samples/tree/master/HostedService

The version of package it uses appears to be the to be the latest version:

<package id="Microsoft.SystemForCrossDomainIdentityManagement" version="2.0.5.95" targetFramework="net452" />

Steps to reproduce:

1. Compile and run application in IIS Express
2. GET - http://localhost:47035/scim/users/?filter=externalId%20eq%20bjensen
3. 500 error response in OP

Additional notes:

Decompiling I was able to identify the following sample user for use in the query from the following line of code from QueryUsers(parameters, filter);:

return string.Equals(filter.ComparisonValue, "**bjensen**", StringComparison.OrdinalIgnoreCase) ? (Resource[])this.SampleUser.ToCollection<Core2EnterpriseUser>().ToArray<Core2EnterpriseUser>() : Enumerable.Empty<Resource>().ToArray<Resource>();

I can see that the code is trying to return this object via the QueryResponseBase class. However, I am not sure where this object is being returned to, but there is a breakage after this, but before the object is serialized and written into the web response.

Any assistance or insights you could provide would be appreciated. Is there a different sample provider that I should try using instead? Documentation is incredibly spartan for this component and most of the insights I have gained have come from decompiling objects like the WebApplicationStarter, ServiceConfigurationBase, Schematized, SampleProvider, ProviderBase, ConsoleMonitor, and so on.

I'm currently stuck and can't figure out how to get this GET request to actually return anything other than a 500 internal server error.

**Comment by craigmcm** [comment]
Thanks for the excellent response.  I’ll get back to you, and I apologize for the misery.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

**Comment by iaiken** [comment]
Hi Craig,

I'm just circling back to this to ensure that this HostedService demo project is still a viable demo as I can't get it to serialize any responses even when I use the Sample Provider and response objects.

I also commented over on the file based provider, which I cannot get to compile due to what appear to be missing classes, however, we can track that issue in the other thread as it pertains to a different demo project.

Sincerely,

Evan

**Comment by craigmcm** [comment]
Evan:

Nothing should be expected to work, I don’t think, until a more current version of the package is published.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

**Comment by craigmcm** [comment]
Hi Evan,

Please try using the samples from : https://github.com/ankitC/AzureAD-BYOA-Provisioning-Samples<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FankitC%2FAzureAD-BYOA-Provisioning-Samples&data=04%7C01%7Canchheda%40microsoft.com%7Cffa80be7fe10482570d408d691187489%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636855931557346442%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=lY5%2FD5wZOsUOeeOOBwIrbnNXN%2BDrk6OMcxLA9oouKHc%3D&reserved=0>

These ones do not have the issue of missing classes. This repo also has continuous build integrations and as of now, it shows up that the build is in fact succeeding.

[cid:image001.png@01D4C2BE.EEF64A00]

We shall be updating the samples at the official Microsoft Azure GitHub repo in the near future.

Thanks!

Cheers,
Ankit
From: Craig McMurtry <craigmcm@microsoft.com>
Sent: Tuesday, February 12, 2019 8:15 AM
To: Azure/AzureAD-BYOA-Provisioning-Samples <reply@reply.github.com>; Azure/AzureAD-BYOA-Provisioning-Samples <AzureAD-BYOA-Provisioning-Samples@noreply.github.com>
Cc: Comment <comment@noreply.github.com>; Aaron Smalser <asmalser@microsoft.com>; Ankit K Chheda <anchheda@microsoft.com>
Subject: RE: [Azure/AzureAD-BYOA-Provisioning-Samples] Queries to HostedService scim/users/?filter=externalId%20eq%20bjensen results in 500 error (#23)

Evan:

Nothing should be expected to work, I don't think, until a more current version of the package is published.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329
