### ISSUE TITLE
Response StatusCode 409 / User already exists

### ISSUE THREAD

**Issue by sven73a** [Azure/AzureAD-BYOA-Provisioning-Samples#28]
Hi,

In the protocol SCIM definition the following is stated in [paragraph 3.3](https://tools.ietf.org/html/rfc7644#section-3.3):

> If the service provider determines that the creation of the requested
>    resource conflicts with existing resources (e.g., a "User" resource
>    with a duplicate "userName"), the service provider MUST return HTTP
>    status code 409 (Conflict) with a "scimType" error code of
>    "uniqueness", as per Section 3.12.

When I look in the decompiled DLL "Microsoft.SystemForCrossDomainIdentityManagement.Service.dll" (with dotPeek) at `ControllerTemplate<T>` I cannot find that statuscode 409 is returned when a user will be created, I cannot even find which exception I have to throw when a user (user with the same unique name) already exists.

Can SystemForCrossDomainIdentityManagement handle the response when the provider tries to create a user which already exists. If so which exception do I have to throw?
Do you know what Azure AD expect as response when a user already exists when creating a user?

**Comment by craigmcm** [comment]
1.  The controller should not know whether or not a conflict was encountered in the back-end store. That’s the responsibility of the model, which, in this case, is represented by the SCIM provider, or, more concretely, by the IProvider implementation, which might be derived from ProviderBase or BulkRequestProviderTemplate<T> or implemented from scratch. It would be the provider that would throw an HttpResponseException with the 409 status code in the event of a conflict.



  1.  Conflicts should never happen, however; the Azure Active Directory provisioning service should never get a conflict response from a SCIM service. For all entries in the provisioning scope, the Azure Active Directory provisioning service should be the master. If that assumption is true, then if Azure Active Directory has an entry that the directory fronted by the SCIM service already has, then the SCIM service should return that object in response to a query that the Active Directory provisioning service will always make prior to any attempt to POST the entry.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 27 (South), Team Room 1030
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329

**Comment by sven73a** [comment]
Tnx for your quick answer. I am going to do some testing :)

**Comment by sven73a** [comment]
I have aquestion about how to response from the Provider (in our case LDAPProvider) in some scenario's. BTW we use the latest nuget package of Microsoft.SystemForCrossDomainIdentityManagement

Query User based on identifier which cannot be found in the target identity store, example: scim/Groups/a6dda7e1-51c0-4153-9f15-870b256f8be8. It comes in the RetrieveAsync Controller and when not found return null
``` Csharp
public override async Task<Resource> RetrieveAsync(IResourceRetrievalParameters parameters, string correlationIdentifier)
{

....

	var userCheckExistInOu = _accountMgt.GetUser(parameters.ResourceIdentifier.Identifier, IdentityType.Guid);
	if (userCheckExistInOu == null)
	{
		LogWrapper.LogWarning(new InformationNotification($"User: {parameters.ResourceIdentifier.Identifier} not found.", correlationIdentifier), methodName, parameters.Path);
		return null;
	}
	
...
}
```
This result in the log is the following response:

> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
>    at Microsoft.SystemForCrossDomainIdentityManagement.ControllerTemplate`1.<Get>d__4.MoveNext()
> 
> 
> 
> 
> StatusCodeNotFound
> Reason: Not Found

I would expect something like this:

``` Json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "404",
    "detail": "Resource 23B51B0E5D7AE9110A49411D@7cca31655d49f3640a494224 not found"
}
```
And I also don't see in the log a line with the text **"Data has been written"**. 

- Is return null the correct response from the Provider which implemented IProvider? 
- Is it correct that "SystemForCrossDomainIdentityManagement" build the response message? Or do I have to do that in the Provider?
- Can I override it some how?

**Comment by sven73a** [comment]
I have aquestion about how to response from the Provider (in our case LDAPProvider) in some scenario's. BTW we use the latest nuget package of Microsoft.SystemForCrossDomainIdentityManagement

Query User based on identifier which cannot be found in the target identity store, example: `scim/Groups/a6dda7e1-51c0-4153-9f15-870b256f8be8`. It comes in the RetrieveAsync Controller and when not found return null
``` Csharp
public override async Task<Resource> RetrieveAsync(IResourceRetrievalParameters parameters, string correlationIdentifier)
{

....

	var userCheckExistInOu = _accountMgt.GetUser(parameters.ResourceIdentifier.Identifier, IdentityType.Guid);
	if (userCheckExistInOu == null)
	{
		LogWrapper.LogWarning(new InformationNotification($"User: {parameters.ResourceIdentifier.Identifier} not found.", correlationIdentifier), methodName, parameters.Path);
		return null;
	}
	
...
}
```
This result in the log is an ERROR:

> System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
>    at Microsoft.SystemForCrossDomainIdentityManagement.ControllerTemplate`1.<Get>d__4.MoveNext()
> 
> 
> 
> 
> StatusCodeNotFound
> Reason: Not Found

The response it self is only 404 response code without content.

I would expect a response with content like this:

``` Json
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": "404",
    "detail": "Resource 23B51B0E5D7AE9110A49411D@7cca31655d49f3640a494224 not found"
}
```
And I also don't see in the log a line with the text **"Data has been written"**. 

- Is return null the correct response from the Provider which implemented IProvider? 
- Is it correct that "SystemForCrossDomainIdentityManagement" build the response message? Or do I have to do that in the Provider?
- Can I override it some how and what does AAD expect for response?

**Comment by mwrf** [comment]
Hi craigmcm,

Thanks for the details here, it was very helpful in debugging a problem we has specifically with Azure AD/Entra. 

Is it better to check for the existence of users first by the user ID instead of usernames?
The username might and can change, and the underlying "user" may be the Same GUID. 

We implement the GUID as the unique identifier, but it appears from the Entra traffic that the lookup is based on userName.

My reading of the RFC: https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.1
is that you should be sending the {id} to check if something exists, not performing a search. 

Some systems may have multiple sources of users, for example. 

Thanks,
